import type { NextConfig } from "next";

// Redirects from the pre-2026 legacy site (old ".html" URL structure at
// /archives/..., /emc/archives/..., etc.) to their matching posts in the
// new archive. Sourced from 6 years of Google Analytics 404 traffic,
// cross-referenced against the archive dataset and, where the old truncated
// slug matched more than one candidate, confirmed against the actual
// archived page content via the Wayback Machine.
const legacyRedirects = [
  { source: "/archives/blog/2014-the-year-of-the-bible.html", destination: "/archive/2014-the-year-of-the-bible", permanent: true },
  { source: "/archives/blog/a-beautiful-and-needed-prayer.html", destination: "/archive/a-beautiful-and-needed-prayer", permanent: true },
  { source: "/archives/blog/a-bigger-circle-in-baltimore-and.html", destination: "/archive/a-bigger-circle-in-baltimore-and-burundi", permanent: true },
  { source: "/archives/blog/a-conservative-bloggers-reasons.html", destination: "/archive/a-conservative-bloggers-reasons", permanent: true },
  { source: "/archives/blog/a-franciscan-benediction.html", destination: "/archive/a-franciscan-benediction", permanent: true },
  { source: "/archives/blog/a-new-kind-of-christianity.html", destination: "/archive/a-new-kind-of-christianity", permanent: true },
  { source: "/archives/blog/a-new-kind-of-pentecostalism-2.html", destination: "/archive/a-new-kind-of-pentecostalism-2", permanent: true },
  { source: "/archives/blog/a-prayer-for-pastors-on-easter.html", destination: "/archive/a-prayer-for-pastors-on-easter", permanent: true },
  { source: "/archives/blog/a-week-of-grieving-part-of-adven.html", destination: "/archive/a-week-of-grieving-part-of-advent", permanent: true },
  { source: "/archives/blog/advent-reflections.html", destination: "/archive/advent-reflections", permanent: true },
  { source: "/archives/blog/an-interesting-discussion-somewh.html", destination: "/archive/an-interesting-discussion-somewhat-peripherally-about-me", permanent: true },
  { source: "/archives/blog/an-interview-with-colby-martin.html", destination: "/archive/an-interview-with-colby-martin", permanent: true },
  { source: "/archives/blog/an-open-letter-to-conservative-c.html", destination: "/archive/an-open-letter-to-conservative-christians-in-the-u-s-on-health-care", permanent: true },
  { source: "/archives/blog/calling-all-calvinists.html", destination: "/archive/calling-all-calvinists", permanent: true },
  { source: "/archives/blog/common-prayer-for-copenhagen.html", destination: "/archive/common-prayer-for-copenhagen", permanent: true },
  { source: "/archives/blog/contraception-hobby-lobby-and-ab.html", destination: "/archive/contraception-hobby-lobby-and-abortion", permanent: true },
  { source: "/archives/blog/convergence-christianity-its-hap.html", destination: "/archive/convergence-christianity-its-happening", permanent: true },
  { source: "/archives/blog/countdown-day-38.html", destination: "/archive/countdown-day-38", permanent: true },
  { source: "/archives/blog/economics-101.html", destination: "/archive/economics-101", permanent: true },
  { source: "/archives/blog/emergent-conversation-update.html", destination: "/archive/emergent-conversation-update", permanent: true },
  { source: "/archives/blog/evangelicals-and-lgbtq-equality.html", destination: "/archive/evangelicals-and-lgbtq-equality", permanent: true },
  { source: "/archives/blog/former-religious-right-activist.html", destination: "/archive/former-religious-right-activist-for-obama", permanent: true },
  { source: "/archives/blog/gone-from-mystery-into-mystery.html", destination: "/archive/gone-from-mystery-into-mystery", permanent: true },
  { source: "/archives/blog/gradye-parsons-to-donald-trump.html", destination: "/archive/gradye-parsons-to-donald-trump", permanent: true },
  { source: "/archives/blog/heres-a-sermon-for-pentecost-sun.html", destination: "/archive/heres-a-sermon-for-pentecost-sunday", permanent: true },
  { source: "/archives/blog/if-youre-getting-criticized.html", destination: "/archive/if-youre-getting-criticized", permanent: true },
  { source: "/archives/blog/if-youve-never-discovered.html", destination: "/archive/if-youve-never-discovered", permanent: true },
  { source: "/archives/blog/in-honor-of-marcus-borg.html", destination: "/archive/in-honor-of-marcus-borg", permanent: true },
  { source: "/archives/blog/its-time-to-turn-the-spotlight-o.html", destination: "/archive/its-time-to-turn-the-spotlight-on-christian-zionism", permanent: true },
  { source: "/archives/blog/more-on-interpreting-matthew-25.html", destination: "/archive/more-on-interpreting-matthew-25", permanent: true },
  { source: "/archives/blog/more-on-sexuality-and-c-s-lewis.html", destination: "/archive/more-on-sexuality-and-c-s-lewis", permanent: true },
  { source: "/archives/blog/my-take-why-i-support-anne-rice.html", destination: "/archive/my-take-why-i-support-anne-rice-but-am-still-a-christian", permanent: true },
  { source: "/archives/blog/nicholas-kristof-tim-keller-chri.html", destination: "/archive/nicholas-kristof-tim-keller-christmas-and-a-key-pastoral-question", permanent: true },
  { source: "/archives/blog/on-the-beatitudes.html", destination: "/archive/on-the-beatitudes", permanent: true },
  { source: "/archives/blog/open-letter-to-worship-songwrite.html", destination: "/archive/open-letter-to-worship-songwriters-updated", permanent: true },
  { source: "/archives/blog/open-letter-to-worship-songwriters.html", destination: "/archive/open-letter-to-worship-songwriters-updated", permanent: true },
  { source: "/archives/blog/parents-and-youth-workers-this-i.html", destination: "/archive/parents-and-youth-workers-this-is-really-amazing", permanent: true },
  { source: "/archives/blog/peter-enns-interview-part-2.html", destination: "/archive/peter-enns-interview-part-2", permanent: true },
  { source: "/archives/blog/politics-and-consciousness.html", destination: "/archive/politics-and-consciousness", permanent: true },
  { source: "/archives/blog/prayer-for-enemies.html", destination: "/archive/prayer-for-enemies", permanent: true },
  { source: "/archives/blog/preaching-in-challenging-times.html", destination: "/archive/preaching-in-challenging-times", permanent: true },
  { source: "/archives/blog/q-r-exegeting-matthew-25.html", destination: "/archive/q-r-exegeting-matthew-25", permanent: true },
  { source: "/archives/blog/q-r-onward-christian-what.html", destination: "/archive/q-r-onward-christian-what", permanent: true },
  { source: "/archives/blog/q-r-romans-13.html", destination: "/archive/q-r-romans-13", permanent: true },
  { source: "/archives/blog/q-r-the-propitiation-question.html", destination: "/archive/q-r-the-propitiation-question", permanent: true },
  { source: "/archives/blog/q-r-you-rob-bell-don-miller-and.html", destination: "/archive/q-r-you-rob-bell-don-miller-and-christianity-today", permanent: true },
  { source: "/archives/blog/song.html", destination: "/archive/song", permanent: true },
  { source: "/archives/blog/steve-knight-on-participatory-ch.html", destination: "/archive/steve-knight-on-participatory-church", permanent: true },
  { source: "/archives/blog/strong-and-benevolent-religious.html", destination: "/archive/strong-and-benevolent-religious-identity-in-egypt", permanent: true },
  { source: "/archives/blog/taking-the-bible-literally-input.html", destination: "/archive/taking-the-bible-literally-input-from-augustine", permanent: true },
  { source: "/archives/blog/teaching-kids-to-walk.html", destination: "/archive/teaching-kids-to-walk", permanent: true },
  { source: "/archives/blog/thank-you-laci.html", destination: "/archive/thank-you-laci-kathy-wendy-and-katherine", permanent: true },
  { source: "/archives/blog/the-ecra-a-modest-proposal.html", destination: "/archive/the-ecra-a-modest-proposal", permanent: true },
  { source: "/archives/blog/the-risen-christ.html", destination: "/archive/the-risen-christ", permanent: true },
  { source: "/archives/blog/the-sex-question-a-new-kind-of-c.html", destination: "/archive/the-sex-question-a-new-kind-of-christianity", permanent: true },
  { source: "/archives/blog/the-smell-of-justice-in-the-morn.html", destination: "/archive/the-smell-of-justice-in-the-morning", permanent: true },
  { source: "/archives/blog/three-crises-of-peace-1.html", destination: "/archive/three-crises-of-peace-1", permanent: true },
  { source: "/archives/blog/to-brighten-your-outlook-for-the.html", destination: "/archive/to-brighten-your-outlook-for-the-week-ahead", permanent: true },
  { source: "/archives/blog/trayvon-and-george-a-tale-of-two.html", destination: "/archive/trayvon-and-george-a-tale-of-two-americas", permanent: true },
  { source: "/archives/blog/were-connected-by-what-we-eat.html", destination: "/archive/were-connected-by-what-we-eat", permanent: true },
  { source: "/archives/blog/what-do-white-evangelicals-stand.html", destination: "/archive/what-do-white-evangelicals-stand-for", permanent: true },
  { source: "/archives/blog/what-i-said-at-the-white-house.html", destination: "/archive/what-i-said-at-the-white-house", permanent: true },
  { source: "/archives/blog/why-you-should-come-to-nashville.html", destination: "/archive/why-you-should-come-to-nashville", permanent: true },
  { source: "/archives/blog/yesterday-i-mentioned.html", destination: "/archive/yesterday-i-mentioned", permanent: true },
  { source: "/archives/books/brians-books/a-generous-orth.html", destination: "/archive/a-generous-orthodoxy", permanent: true },
  { source: "/archives/books/brians-books/everything-must-change.html", destination: "/archive/everything-must-change", permanent: true },
  { source: "/archives/books/brians-books/we-make-the-road-by-walking-2.html", destination: "/archive/we-make-the-road-by-walking-2-ways-it-can-help-you", permanent: true },
  { source: "/archives/books/brians-books/why-did-jesus-moses-the-buddha-a.html", destination: "/archive/why-did-jesus-moses-the-buddha-and-mohammed-cross-the-road-2", permanent: true },
  { source: "/books-by-brian-mclaren/everything-must-change.html", destination: "/archive/everything-must-change", permanent: true },
  { source: "/books-by-brian-mclaren/finding-faith-a-search-for-what.html", destination: "/archive/finding-faith-a-search-for-what-makes-sense", permanent: true },
  { source: "/emc/archives/books/brians-books/a-search-for-what-is-real-findin.html", destination: "/archive/a-search-for-what-is-real-finding-faith", permanent: true },
  { source: "/emc/archives/books/brians-books/finding-faith-a-search-for-what.html", destination: "/archive/finding-faith-a-search-for-what-makes-sense", permanent: true },
  { source: "/emc/archives/imported/an-interview-on-christian-publis.html", destination: "/archive/an-interview-on-christian-publishing-and-postmodernity", permanent: true },
  { source: "/emc/archives/imported/an-open-letter-to-chuck-colson.html", destination: "/archive/an-open-letter-to-chuck-colson", permanent: true },
  { source: "/emc/archives/imported/dallas-morning-news-interview-wi.html", destination: "/archive/dallas-morning-news-interview-with-brian-mclaren", permanent: true },
  { source: "/emc/archives/imported/dorothy-on-leadership.html", destination: "/archive/dorothy-on-leadership", permanent: true },
];

const nextConfig: NextConfig = {
  async redirects() {
    return legacyRedirects;
  },
};

export default nextConfig;
